### PR TITLE
Fix vulnerabilities + Babel 7 + Extras

### PR DESCRIPTION
**Pull request by sibiraj-sr**
I was about to propose a change, when cloned the repo and did `npm install` there are about `~1.5k` vulnerabilities reported by npm audit. Hence this PR and some extras.

file-manager-webpack-plugin

**Changes Proposed**

- [x] all packages in root dir is updated to latest version
- [x] babel 7
- [x] rollup stable version
- [x] removed parser option from `prettier` config as it defaults to `babel` (renamed from `babylon`)
- [x] browser configuration for babel is moved to `.browserslistrc` so that it can be shared
- [x] .travis.yml had the minimum node version 8 hence took the liberty of updating packages also added to engines field in package.json.
- [x] updated packages in tests dir 
- [x] removed few unused packages

I am not sure of the minimum node version support of this package. but these changes will require `node > 8`.

### CODE REVIEW

**Comment by sibiraj-sr** [comment]
@gregnb travis tests seems to be not triggered...

**Comment by sibiraj-sr** [comment]
@gregnb

**Comment by sibiraj-sr** [comment]
@gregnb

**Comment by gapipro** [comment]
Can you get this merged....

**Comment by devghost** [comment]
Until this get merged you could use https://www.npmjs.com/package/filemanager-webpack-plugin-fixed

**Comment by sibiraj-sr** [comment]
@gregnb Incase you need a hand in maintaining the package. I can help.

**Comment by gregnb** [comment]
@sibiraj-sr I do. I added you

**Comment by gregnb** [comment]
@sibiraj-sr what's your NPM username?

**Comment by sibiraj-sr** [comment]
@gregnb . thanks. This is my official account. I won't be active here mostly. My Personal profile is https://github.com/sibiraj-s. Can you add that. 

Sorry for the trouble.

**Comment by sibiraj-sr** [comment]
My NPM account https://www.npmjs.com/~sibiraj-s

**Comment by sibiraj-s** [comment]
Thanks for the invite,

**Comment by sibiraj-s** [comment]
Published in v3.0.0-aplha.0. Will soon publish v3 stable.

**Pull request merged**
