### PR TITLE
Updated to support Webpack 4.

### PR DESCRIPTION
**Pull request by dphoebus**
The compiler.plugin() method is really the only issue.  Had to update to use the new .hooks now.

### CODE REVIEW

**Comment by gregnb** [comment]
Cool man I've been thinking about this lately. We still need to support older versions of Webpack so how above detecting if hooks is available so then we know this is for version 4 and only use it then otherwise just use compiler.plugin

**Comment by dphoebus** [comment]
Used code from CopyWebpackPlugin source as an [example](https://github.com/webpack-contrib/copy-webpack-plugin/blob/65314cd8fbb6825bfbae228eae7356e0c7aaaca8/src/index.js#L158l).

**Comment by gregnb** [comment]
Excellent work! Nice being resourceful to look at how it's already been done. If it passes these latest tests I'll give it one more test locally and publish this out ASAP

**Comment by gregnb** [comment]
No problem man!

**Comment by gregnb** [comment]
Merged. Thanks again!

**Comment by dphoebus** [comment]
Thank you!  Great plugin!

**Pull request merged**
